# Start cleaning data

In [5]:
import pandas as pd
import calendar
df = pd.read_csv("../Initial Data/Madrid Daily Weather 1997-2015.csv")

### Add column day, month, year

- Change date format  to yy/mm/dd

- Create year month day title (For easy to call)

In [6]:
df['CET'] = pd.to_datetime(df['CET'], format='%Y-%m-%d')
df['Day'] = df['CET'].dt.day
df['Month'] = df['CET'].dt.month
df['Month'] = df['Month'].apply(lambda x: calendar.month_name[x])
df['Year'] = df['CET'].dt.year
df

,CET,Max TemperatureC,Mean TemperatureC,Min TemperatureC,Dew PointC,MeanDew PointC,Min DewpointC,Max Humidity,Mean Humidity,Min Humidity,...,Max Wind SpeedKm/h,Mean Wind SpeedKm/h,Max Gust SpeedKm/h,Precipitationmm,CloudCover,Events,WindDirDegrees,Day,Month,Year
0,1997-01-01,7.0,4.0,2.0,5.0,3.0,2.0,100.0,95.0,76.0,...,13,6,NaN,0.00,6.0,NaN,229,1,January,1997
1,1997-01-02,7.0,3.0,0.0,6.0,3.0,0.0,100.0,92.0,71.0,...,26,8,47.0,0.00,5.0,Rain,143,2,January,1997
2,1997-01-03,5.0,3.0,2.0,5.0,1.0,-1.0,100.0,85.0,70.0,...,27,19,NaN,0.00,6.0,Rain-Snow,256,3,January,1997
3,1997-01-04,7.0,3.0,-1.0,-2.0,-3.0,-4.0,86.0,63.0,49.0,...,27,19,40.0,0.00,2.0,NaN,284,4,January,1997
4,1997-01-05,2.0,0.0,-1.0,2.0,0.0,-3.0,100.0,95.0,86.0,...,14,6,NaN,0.00,7.0,Snow,2,5,January,1997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6807,2015-12-27,14.0,7.0,-1.0,6.0,2.0,-2.0,100.0,77.0,30.0,...,14,6,NaN,0.00,8.0,Fog,38,27,December,2015
6808,2015-12-28,15.0,8.0,2.0,8.0,4.0,1.0,100.0,78.0,34.0,...,27,8,45.0,0.51,7.0,Rain,243,28,December,2015
6809,2015-12-29,11.0,8.0,5.0,9.0,7.0,5.0,100.0,89.0,66.0,...,14,8,32.0,2.03,5.0,Fog-Rain,190,29,December,2015
6810,2015-12-30,9.0,8.0,6.0,7.0,6.0,5.0,93.0,87.0,70.0,...,14,5,34.0,0.00,6.0,NaN,256,30,December,2015
6811,2015-12-31,12.0,10.0,7.0,10.0,8.0,7.0,100.0,90.0,70.0,...,14,6,NaN,0.25,6.0,Rain,313,31,December,2015

- Export csv file that do not delete outliner

In [4]:
df.to_csv('../Coding/Madrid Daily Weather 1997-2015 clean data add column.csv', index = False)

### Outliner

- Delete Events that only happend once (happend 1 time is hard to calculate and prediction)

In [4]:
#Delete Events once happend
delete_events = df[' Events'].value_counts() 
# filter events that happend grater than 1 time
df = df[df[' Events'].isin(delete_events[delete_events > 1].index)]
# check current events
df[' Events'].value_counts()

 Events
Rain                      1140
Rain-Thunderstorm          247
Fog                        233
Fog-Rain                    69
Thunderstorm                45
Rain-Snow                   33
Snow                        14
Rain-Hail-Thunderstorm       7
Fog-Snow                     4
Name: count, dtype: int64

- Export csv file that delete outliner

In [11]:
df.to_csv('../Coding/Madrid Daily Weather 1997-2015 clean data.csv', index = False)